baseURL = 'https://sayap.in/'
staticDir = ['static']
languageCode = 'en-us'
title = 'Sayap.in'
theme = "archie"

copyright = "© Michael Sayapin"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 10

[markup.goldmark.renderer]
unsafe = true

[params]
	mode = "auto"
	subtitle = "`Michael Sayapin v.1.0.0 verbal-textual output:`"
	customcss = ["css/sayap.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
